# The use of the correct number of significant figures in calculations. {#sec-chapter2}

In @sec-chapter1 we have learnt about significant figures and why they are important in understanding the confidence we have in a value.

Now we need to learn the rules to how many significant figures we should use after doing calculations.

There are different rules for how we handle significant figures depending upon the type of calculation we have done. Freqently we may have more than one step in a calculation, and therefore we need to be concious of the appropriate significant figures in each step.

## Significant figures in addition and subtraction {#sec-sfaddsub}

When adding or subtracting values, the number of decimal places in the result should be the same as the value with the least number of decimal places in your calculation.

We cannot add precision, I can't measure something with a meter rule with 1 cm increments, a 15 cm rule with 1 mm increments and a micrometer with 1 μm increments and then add them together and expect to have a result with 1 μm precision. The result will be limited by the least precise measurement.

::: {#tip-scales .callout-tip title="Significant figures in addition and subtraction."}
When adding or subtracting values, the number of decimal places in the result should be the same as the value with the least number of decimal places in your calculation.
:::

::: {.callout-caution title="Examples of significant figures in addition and subtraction."}

- Convert 20 ºC to Kelvin.

We know our measured temperature to 0 decimal places, therefore our answer should be to 0 decimal places.

T = 20 ºC + 273.15 K = 293 K

- An ideal gas was heated with 1.75 kJ of energy an allowed to do 250 J of work. What is the change in internal energy of the gas?

In this case we have different units, so if we convert 250 J to kJ we have 0.250 kJ. The least number of decimal places is 2, therefore our answer should be to 2 decimal places.

$\Delta U = 1.75 \textrm{ kJ} - 0.250 \textrm{ kJ} = 1.50 \textrm{ kJ}$

This unit conversion kJ to J (or vice versa) is common in thermodynamics calculations where $\Delta H$ is usually reported in kJ mol$^{-1}$, but $\Delta S$ is usually reported in J K mol$^{-1}$.

It is easy to forget the significant zero at the end of this number as usually our calculator will not report it, but including it gives us our answer to a  higher, more appropriate, precision.

:::

### Exercises with addition and subtraction examples.

#### Self check on our learning so far. {#sec-SelfcheckSFaddsub}

::: {.callout-note collapse="true"}
## What is 15.4 g + 0.16 g to the correct number of significant figures?

15.6 g

The rule for adding and subtracting is that the answer should be reported to the least number of decimal places in the calculation. In this case 15.4 g has 1 decimal place, and 0.16 g has 2 decimal places, so our answer should be reported to 1 decimal place.

:::

::: {.callout-note collapse="true"}
## What is -154.3 kJ mol$^{-1}$ + 894.2 J mol$^{-1}$ to the correct number of significant figures?

-153.4 kJ mol$^{-1}$

Here we have different units, so if we convert 894.2 J mol$^{-1}$ to kJ mol$^{-1}$ we have 0.8942 kJ mol$^{-1}$. 

Now we can compare the number of decimal places in each value. -154.3 kJ mol$^{-1}$ has 1 decimal place, and 0.8942 kJ mol$^{-1}$ has 4 decimal places, so keeping the fewest decimal places, our answer should be reported to 1 decimal place.

:::

The following are molar masses of some common elements. Use these values to answer the following questions.

|| $R_A$ / g mol$^{-1}$ |
|:---:|:------:|
| H | 1.00794 |
| C | 12.011 |
| O | 15.9994 |
| N | 14.0067 |
| Cl | 35.45 |

: A selection of atomic masses of common elements. {#tbl-atomicmassescommon}    

:::{.callout-note collapse="true"}
## What is the molar mass of HCl to the correct number of significant figures?

36.46 g mol$^{-1}$

35.45 g mol$^{-1}$ + 1.00794 g mol$^{-1}$ = ~~36.45794 g mol~~$^{-1}$
 = 36.46 g mol$^{-1}$


Cl has the least number of decimal places (2), so our answer should only be reported to 2 decimal places.
:::

Given we should now be in the habit of reporting our answers to the correct number of significant figures, this is no longer going to be asked in the following exercises, but we should still be concious of the number of significant figures in our answers.

:::{.callout-note collapse="true"}
## What is the molar mass of C$_2$H$_5$OH?

46.064 g mol$^{-1}$

Carbon's molar mass has 3 decimal places, hydrogen's molar mass has 5 decimal places and oxygen's molar mass has 4 decimal places. 

In addition questions our answer should be reported to the fewest decimal places, which in this case is 3.
:::

:::{.callout-note collapse="true"}
## What is the molar mass of C$_6$H$_{12}$O$_6$?

180.158 g mol$^{-1}$

Once you get used to the idea of handling signficant figures you will be able to perform your calculations, then correct your values to the correct number of significant figures when reporting.

Here Carbon has 3 decimal places, so the answer should be reported to 3 decimal places, even if the value coming from a calculator would be 180.15768.
:::

:::{.callout-note collapse="true"}
## What is the molar mass of C$_{12}$H$_8$N$_2$?

180.209 g mol$^{-1}$


Again carbon limits the number of decimal places to give in our answer.
:::

:::{.callout-note collapse="true"}
## What is the molar mass of C$_{12}$H$_{22}$O$_{11}$?

342.300 g mol$^{-1}$

It is important to remember to include significant zeros if they are there. These are easy to remember because there were non zero numbers after them, but remember to write them down.
:::


#### Self assessment question on significant figures in addition and subtraction.

Please remember you can refresh this question.

```{=html}
<iframe src="https://numbas.mathcentre.ac.uk/question/210135/sig-figs-add-sub/embed/?token=504985f6-ad65-4e25-8415-4a61de7d9766" width=100% height="300"></iframe>
```


## Significant figures in multiplication and division {#sec-sfmuldiv}

When multiplying or dividing values, the number of significant figures in the result should be the same as the value with the least number of significant figures in your calculation.

First we need to quickly count the number of significant figures in each value. If we have a unit conversion (such as mm to cm) then this is 'exact' and does not change the number of significant figures in our value. Some unit conversions have limited significant figures, others are precise. In either case it is always a good habit to use more significant figures in constants than in our other values.

::: {#tip-scales .callout-tip title="Significant figures in multiplication and division."}
When multiplying or dividing values, the number of significant figures in the result should be the same as the value with the least number of significant figures in your calculation.
:::

::: {.callout-caution title="Example of significant figures in multiplication and division - the ideal gas law."}

- Determine the number of moles of gas in a cylinder with a volume of exactly 2.52 L at a pressure of 50.24 bar and a temperature of 273 K.

Here we need to do a couple of unit conversions to get our values into base SI units. 

The volume is already in L, which is a derived unit, but we need to convert it to m$^3$. 1 L $\equiv$ 1 dm$^3$ = 1 x 10$^{-3}$ m$^3$, so we have 2.52 L = 2.52 x 10$^{-3}$ m$^3$. 
This is an exact conversion, so the number of significant figures in our value does not change.
Recall that the volume is described as "exactly" 2.52 L, so we have 'infinite' significant figures in our volume.

The pressure is in bar, which is not an SI unit, so we need to convert it to Pa. 1 bar = 1 x 10$^5$ Pa, so we have 50.24 bar = 5.024 x 10$^6$ Pa. This is also an exact conversion.
The pressure has 4 significant figures, so our pressure in bar will also have 4 significant figures.

Using the ideal gas law, we can calculate the number of moles of gas in the cylinder.

$pV = nRT$
so $n = \frac{pV}{RT}$

Putting in our values:

$$n = \frac{5.024 \times 10^6 \textrm{ Pa} \times 2.52 \times 10^{-3} \textrm{ m}^3}{8.31446 \textrm{ J K}^{-1} \textrm{ mol}^{-1} \times 273 \textrm{ K}}$$

$n = 5.58 \textrm{ mol}$

Temperature only has 3 significant figures, so our answer should be reported to 3 significant figures.
:::


::: {.callout-caution title="Example of significant figures in multiplication and division - heat capacity."}

- Determine the energy put into a system when a 1.000 kg block of copper is heated from 20.16 ºC to 60.52 ºC. The specific heat capacity of copper is 385 J kg$^{-1}$ K$^{-1}$.

We can calculate the energy put into the system using the equation:

$q = m c \Delta T$

First we need to determine the change in temperature, $\Delta T$.

$\Delta T = T_{\textrm{final}} - T_{\textrm{initial}}$

$\Delta T = 60.52 ºC - 20.16 ºC = 40.36 ºC$

We've followed the rules for addition and subtraction, so our answer has 2 decimal places, which is the same as the least number of decimal places in our calculation.

Now we can calculate the energy put into the system, $q$.

$q = 1.000 \textrm{ kg} \times 385 \textrm{ J kg}^{-1} \textrm{ K}^{-1} \times 40.36 \textrm{ K}$

The mass has 4 significant figures, the specific heat capacity has 3 significant figures, and the temperature change has 4 significant figures. The least number of significant figures in our calculation is 3, so our answer should be reported to 3 significant figures.

$q = 15.5 \textrm{ kJ}$

Note: I've changed my units to kJ to make reporting to 3 significant figures easier. If I had left my answer in J, I would have reported it as 15.5 $\times$ 10³ J, which is not as clear (and is more to type).
:::

## Exercises with multiplication and division examples.

### Self check on our learning so far. {#sec-SelfcheckSFmultdiv}

:::{.callout-note collapse="true"}
## If each side of a rectangle was measured to be 2.34 cm and 1.2 cm, what is the area?

A = 2.8 cm$^2$

The area of a rectangle is given by $A = l \times w$, so from our calculator we get a value of 2.808 cm$^2$. Since one of our sides only has 2 significant figures, using our rule of using the fewest significant figures, our answer should be reported to 2 significant figures.
:::

:::{.callout-note collapse="true"}
## What is the volume of a cylinder with a diameter of 2.3 cm and a height of 12.4 cm?

V = 52 cm$^3$

On the surface this is an easy calculation following our rules of significant figures we retain the fewest significant figures in our answer, which is 2. 

You might be tempted to use the radius of the circle, and 'half' the diameter, but in doing this we can get into a mess with our significant figures because we can't gain significant figures by dividing by 2. 

Instead we can use the diameter directly in our calculation, $V = \frac{\pi d^2 h}{4}$ which simplifies the significant figure handling.

This shows that is is often easiest to use algebraic rearrangements to avoid having to do extra calculations which may introduce complications in our consideration of significant figures.
:::

::: {.callout-note collapse="true"}
## Determine the rate constant of diffusion, $k_d$ at 278 K, if the viscosity of the medium, $\eta$, is 1.518 mPa s, given $k_d = \frac{8RT}{3\eta}.

$k_d = 4.06 \times 10^{6}$ m$^3$ s$^{-1}$ = 4.06 \times 10$^{9}$ dm$^3$ s$^{-1}$

This is a more challenging question as you won't hve come across this equation before, but the principles are the same. This is a multiplication and division question, so we need to consider the number of significant figures in each value, and report our answer to the fewest number of significant figures in our calculation.

The integers, 8 and 3 are exact values, so can be considered to have infinite significant figures.

When values are large some poeple want to write 4 060 000 (3sf) but given our rule that if you write a digit it is significant this answer is actually 7 significant figures.
:::

## Significant figures in logarithms {#sec-sflog}

Significant figures in logs and lns are a little different to the rules for addition, subtraction, multiplication and division because we have to think about the 'value' when accounting for how many significant figures we have in our answer.

::: {#tip-scales .callout-tip title="Significant figures in logs and lns."}
When taking logs we usually gain 1 significant figure, however if the ‘logged value’ is between 1 and the base then we do not gain a significant figure.
:::

Practically what does this mean? and why the do we sometimes gain a significant figure? The following example using $\log_{10}$ will help to explain this.

::: {.callout-caution title="Example of significant figures in logs and lns."}

Determine $\log (2.234)$, $\log(22.34)$ and $\log(223.4)$ to the correct number of significant figures.

Our first example is $\log(2.234)$. The value of $\log(2.234)$ is 0.3490831688.... 

The value we are taking the log of has 4 significant figures, so our answer should have 4 significant figures. Therefore we report our answer as 0.3491.

Now, if I take the log of 22.34 I can also write this as $\log(2.234 \times 10^1)$.

Using our 'rules of logs', we can write this as $\log(2.234) + \log(10^1) = 0.3491 + 1 = 1.3491$.

Since our value of $\log(10^1)$ is an exact value, it can be considered to have infinite significant figures, and we can add these values according to the rules in @sec-sfaddsub.

Finally, if I take the log of 223.4 I can also write this as $\log(2.234 \times 10^2)$. The value we are taking the log of has 4 significant figures, so our answer should have 4 significant figures. Therefore we report our answer as 2.3491.

You can see why we gain a significant figure when taking the log of a value greater than 10, but not when taking the log of a value less than 10. The 'value' of the number we are taking the log of is important in determining how many significant figures we have in our answer.

The same principle works if we have very small numbers, for example $\log(0.002234)$ which we can write as $\log(2.234 \times 10^{-3}) = \log(2.234) + \log(10^{-3}) = 0.3491 - 3 = -2.6509$.
:::

