# The standard error {#sec-standarderror}

In @sec-standarddeviation we learned about the standard deviation, which tells us about the spread of data. No matter how careful we are in taking measurements this spread will always exist, and can only be changed by using a different method or technique. 

We of course have only been able to 'guess' our true mean, because we only measure a sample of the data, and we use the sample standard deviation to 'hedge our bets'. However this standard deviation (sample or population) shouldn't change as we increase the number of measurements we take, it is a property of the data and the method used to collect it, but our confidence in the mean should increase as we take more measurements.

This is where the standard error, $\sigma_{\bar{x}}$, comes in. The standard error is a measure of how confident we are in our sample mean, and it is calculated using the formula:

:::{#tip-mean .callout-tip title="Calculating the standard error, $\sigma_{\bar {x}}$."}
$\sigma_{\bar{x}} = \frac{s}{\sqrt{n}}$
:::


where $s$ is the sample standard deviation and $n$ is the number of measurements.

Ideally we should use the population standard deviation, $\sigma$, but logically if we knew 'all' of the data, we would know the mean of that data exactly and there would be little need for an error on this value.

Whilst formally called the *standard error of the mean*, we often just refer to it as the 'error' or 'uncertainty' in the mean. As we increase the number of measurements, $n$, the sample and population standard deviations converge, the standard error will decrease, and our confidence in the mean will increase.

## Significant figures in the standard error {#sec-sigfigstandarderror}

When we calculated the standard deviation in @sec-standarddeviation we learned that we could report the standard deviation to the same precision as the data used to calculate it. So in some of our examples we reported standard deviations to 1 significant figure, others 2, and there is no reason why we can't report to more significant figures if the data set allows it.

However, when we calculate a standard error, we only ever report it to 1 significant figure, and in calculating the value we **always** round up. Even a calculated standard error value of 0.1002 would round up to be reported as 0.2. This is because the standard error is a measure of our confidence in the mean, and we don't want to give a false sense of precision.


:::{.callout-caution title="Calculating the standard error from a sample standard deviation."}

Determine the standard error of the mean when the sample standard deviation is 0.56 and the number of measurements is 4.

$\sigma_{\bar{x}} = \frac{s}{\sqrt{n}}$

Our sample standard deviation, $s$ = 0.56 and our number of measurements, $n$ = 4.

$\sigma_{\bar{x}} = \frac{0.56}{\sqrt{4}}$

$\sigma_{\bar{x}} = 0.28$ which needs to be rounded up to just one significant figure:

$\sigma_{\bar{x}} = 0.3$

:::

I will note here that although practically we would only ever have 1 significant figure in our standard error you may see examples in the (physics) literature where the standard error is reported to 2 significant figures. This is usually because these uncertainties have been calculated from thousands of measurements, indicating a high level of precision and a high confidence in their mean. In our practical work we can never hope to achieve this level of precision and so will only ever report our standard error to 1 significant figure.

### Exercises calculating standard error.

#### Self check on our learning so far. 


:::{.callout-note collapse="true"}
## Determine the standard error of the mean when the sample standard deviation is 0.46 and the number of measurements is 3.

$\sigma_{\bar{x}} = 0.3$

$\sigma_{\bar{x}} = \frac{s}{\sqrt{n}}$

Our sample standard deviation, $s$ = 0.46 and our number of measurements, $n$ = 3.

$\sigma_{\bar{x}} = \frac{0.46}{\sqrt{3}}$

$\sigma_{\bar{x}} = 0.265...$ which needs to be rounded up to just one significant figure:

$\sigma_{\bar{x}} = 0.3$
:::

:::{.callout-note collapse="true"}
## Determine the standard error of the mean when the sample standard deviation is 2.34 and the number of measurements is 5.

$\sigma_{\bar{x}} = 2$

$\sigma_{\bar{x}} = \frac{s}{\sqrt{n}}$

Our sample standard deviation, $s$ = 2.34 and our number of measurements, $n$ = 5.

$\sigma_{\bar{x}} = \frac{2.34}{\sqrt{5}}$

$\sigma_{\bar{x}} = 1.046...$ which needs to be rounded up to just one significant figure:

$\sigma_{\bar{x}} = 2$

This might not *feel* right, but remember that the standard error is a measure of our confidence in the mean, and we don't want to give a false sense of precision.
:::

## How standard error affects precision {#sec-errorprecision}

We have said that when we report a standard error we always round up to 1 significant figure, but this may mean that the precision of our mean is different to the stardard error we have calculated. Therefore, if this is the case, we need to reduce the precision of our calculated mean to reflect the precision of our error or uncertainty.

So if we have calculated a mean of 2.37 and then a standard error of 0.4, we would reduce the precision of our mean to 2.4.

:::{.callout-caution title="Adjusting a mean to match the precision of its standard error."}

A sample was measured 3 times and the mean was calculated to be 101.25, with a standard deviation of 2.54. Calculate the standard error and adjust the mean to match the precision of the standard error.

First we need to calculate the standard error:

$\sigma_{\bar{x}} = \frac{s}{\sqrt{n}}$

Our sample standard deviation, $s$ = 2.54 and our number of measurements, $n$ = 3.

$\sigma_{\bar{x}} = \frac{2.54}{\sqrt{3}}$

$\sigma_{\bar{x}} = 1.46...$ which needs to be rounded up to just one significant figure:

$\sigma_{\bar{x}} = 2$

Our 'uncertainty' is 2, and so we should loose both decimal places in our mean.

$\bar{x} = 101$
:::

Again, this might not *feel* right, but we should never be reporting values to an unrealistically high precision, as this precision is our first indication of our confidence in the mean. If we have good equipment that can record values to a high precision, but our repeatabiity is less good (and our standard deviation and consequently our standard error is large) then this needs to be reflected in the data we are reporting.

:::{.callout-note collapse="true"}
## Determine the standard error and correct the mean if necessary for the following data set: $\bar{k} = 3.2 \times 10^8$ s$^{-1}$, $n$ = 3, $s = 0.8 \times 10^8$ s$^{-1}$.  

$\bar{k} = 3.2 \times 10^8$ s$^{-1}$
$\sigma_{\bar{k}} = 0.5 \times 10^8$ s$^{-1}$

$\sigma_{\bar{x}} = \frac{s}{\sqrt{n}}$

Our sample standard deviation, $s$ = 0.8 \times 10^8$ s$^{-1}$ and our number of measurements, $n$ = 3.

$\sigma_{\bar{k}} = \frac{0.8 \times 10^8}{\sqrt{3}}$

$\sigma_{\bar{k}} = 0.461... \times 10^8$ s$^{-1}$ which needs to be rounded up to just one significant figure:

$\sigma_{\bar{k}} = 0.5 \times 10^8$ s$^{-1}$

This means that our standard error is already to the same precision as our mean.
:::

:::{.callout-note collapse="true"}
## Determine the standard error and correct the mean if necessary for the following data set: $\bar{A}$ = 0.245, $n$ = 4, $s$ = 0.034.  

$\bar{A} = 0.24$
$\sigma_{\bar{A}} = 0.02$

$\sigma_{\bar{x}} = \frac{s}{\sqrt{n}}$

Our sample standard deviation, $s$ = 0.034 and our number of measurements, $n$ = 4.

$\sigma_{\bar{A}} = \frac{0.034}{\sqrt{4}}$

$\sigma_{\bar{A}} = 0.017...$ which needs to be rounded up to just one significant figure:

$\sigma_{\bar{A}} = 0.02$

This means that our standard error is in the second decimal place, and so we need to reduce the precision of our mean to match this.

Without any other information about how the mean was calculated (and therefore if it isn't 'exactly' 0.245) we should reduce the precision of our mean to 2 decimal places, and so using 'round to even' we would report our mean as 0.24.
:::